# Site settings
title: &title Kuyil Carnatic Apps
email: admin@kuyil.org
description: > # this means to ignore newlines until "baseurl:"
    Apps crafted for Carnatic
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

apps:
    shruti:
        email: shruti@kuyil.org
        link: https://play.google.com/store/apps/details?id=org.kuyil.shruti
        full_name: "Shruti Carnatic Tuner"
        short_name: "Shruti"
        caption: "Carnatic Tuner"
        code_name: "shruti"
        logo: /images/shruti_logo.svg
        seal: /images/shruti_seal.png
        description: "Instantly see the swaram you're singing or playing. Tune any instrument accurately. Perfect your singing and playing."
    sadhakam:
        email: sadhakam@kuyil.org
        link: https://play.google.com/store/apps/details?id=org.kuyil.sadhakam
        full_name: "Sadhakam: Carnatic Swara Gnanam Practice"
        short_name: "Sadhakam"
        caption: "Carnatic Swara Gnanam Practice"
        code_name: "sadhakam"
        logo: /images/sadhakam_logo.svg
        seal: /images/sadhakam_seal.png
        description: "Easily improve your swara gnanam with interactive exercises. Develop the skill to identify swarams from what you hear."
    shrutibox:
        email: shrutibox@kuyil.org
        link: https://play.google.com/store/apps/details?id=org.kuyil.shrutibox
        full_name: "Pocket Shruti Box: Carnatic Tambura"
        short_name: "Pocket Shruti Box"
        caption: "Carnatic Tambura"
        code_name: "shrutibox"
        logo: /images/shrutibox_logo.svg
        seal: /images/shrutibox_seal.png
        description: "Concert grade shruti box app. Authentic tambura sound. Very accurate. Clear even on phone speakers. Sounds great with external speakers and headphones."

# seo
url: https://kuyil.org

logo: /images/kuyil_logo.svg 

twitter:
    username: kuyilorg
    card: summary
    link: &twitter https://twitter.com/kuyilorg

facebook:
    publisher: https://www.facebook.com/kuyilorg/
    link: &facebook https://www.facebook.com/kuyilorg/

youtube:
    link: &youtube https://www.youtube.com/c/KuyilCarnaticApps

googleplay:
    link: &googleplay https://play.google.com/store/apps/developer?id=Kuyil

telegram:
    link: &telegram https://telegram.me/kuyil

social: #TODO check if these appear in seo
    name: *title
    links:
        - *twitter
        - *facebook
        - *youtube
        - *googleplay
        - *telegram

# site level variables
new_tab: 'target="_blank" rel="noopener noreferrer"'
