# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kuyil.Org
tagline:             ''
description:         'A very nice description of <em>Kuyil</em>'
url:                 http://kuyil.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              kuyil.org
  url:               https://twitter.com/KuyilOrg
  email:             admin@kuyil.org

# Custom vars
